blank_issues_enabled: false
contact_links:
  - name: Bug Report 
    url: https://github.com/cdunkers/sandbox/issues/new?template=templates/bug_report.md&projects=cdunkers/1
    about: Create a report to help us improve
  - name: Feature Request
    url: https://github.com/cdunkers/sandbox/issues/new?template=templates/feature_request.md&projects=cdunkers/1
    about: Suggest and idea for this project
  - name: Task
    url: https://github.com/cdunkers/sandbox/issues/new?template=templates/task.md&projects=cdunkers/1
    about: Describe a piece of work
