#!/bin/bash

FORMATTER="clang-format-6.0"
FORMAT="$(which $FORMATTER)"
top_lvl=$(git rev-parse --show-toplevel)
fmt_cyan='\033[0;36m'
fmt_norm='\033[0m'

if [ -z "$FORMAT" ]; then
	echo "$FORMATTER not found, unable to format your code."
    # do not exit with error - if the formatter is not installed, we still want
    # the commit to succeed.
    exit 0
fi

for line in $(git diff --name-only --cached); do
    if [[ $line == *.cc || $line == *.hh ]]; then
        echo -e "${fmt_cyan}Files to format:\n${top_lvl}/${line}${fmt_norm}"
        "$FORMAT" -i -style=file "${top_lvl}/${line}"
    fi
done

exit 0
