name: Auto Assign to Project

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to Sandbox Project
    steps:
    - name: Assign NEW issues and NEW pull requests to Sandbox Project
      uses: srggrs/assign-one-project-github-action@1.2.0
      with:
        project: 'https://github.com/users/cdunkers/projects/1'

